# Generated by Django 5.1.4 on 2025-01-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webhooks',
            new_name='Webhook',
        ),
    ]
